model:
  type: const
  translation: [5., 6.]
  num: 100
  std_dev: [1., 1.]

# type: line
# a: 2.
# b: 5.
# start: -50.
# end: 50.
# step: 0.5
# std_dev: [0., 1.0]

# type: curve2d
# start: -10.
# end: 10.
# step: 1.0
# a: 1.0
# b: 1.0
# c: 1.0
# # dを有効にすると3次関数
# d: 1.0
# std_dev: [0., 1.0]

# type: ellipse
# a: 5.
# b: 5.
# rotation: 0.0 # rad
# translation: [5., 6.]
# theta_start: 0.
# theta_end: 6.3
# theta_step: 0.06
# std_dev: [0., 2.0]

# type: michaelis_menten
# b1: 0.362
# b2: 0.556
# start: 0.001
# end: 10.
# step: 0.2
# std_dev: [0., 0.001]

# type: cos
# a: 4.
# b: 5.
# start: -10.
# end: 10.
# step: 0.2
# std_dev: [0., 1.0]

  # plot: True
