model:
  type: curve2d
  start: -10.
  end: 10.
  step: 1.0
  a: 1.0
  b: 1.0
  c: 1.0
  # dを有効にすると3次関数
# d: 1.0

noise_model:
  type: gaussian
  sigma: [0., 3.]

saver:
  type: cv
  output_path: /tmp/data_curve2d.yaml

plot: True
