model:
  type: michaelis_menten
  b1: 0.9
  b2: 0.2
  start: 0.
  end: 10.
  step: 0.2

noise_model:
  type: gaussian
  sigma: [0., 0.05]

saver:
  type: cv
  output_path: /tmp/data_michaelis_menten.yaml

plot: True
