#!/usr/bin/env python
# -*- coding: utf-8 -*-

from fgs_opt_data_generator import generator
from sys import exit, argv


if __name__ == '__main__':
    if len(argv) != 2:
        print('usage: rosrun fgs_opt_data_generator generate_2d config_path')
        exit(-1)

    generator.generate_2d(argv[-1])
#   try:
#       generator.generate_2d(argv[-1])
#   except Exception as e:
#       print(e.message)
#       exit(-1)

    exit(0)
