model:
# type: const2d
# x: 3.
# y: 5.
  type: line2d
  a: 5.
  b: 2.
# type: curve2d_2order
# a: 1.
# b: 2.
# c: 3.
# type: curve2d_3order
# a: 1.
# b: 2.
# c: 3.
# d: 4.
# type: circle2d
# x: 3.
# y: -1.
# r: 2.
# type: michaelis_menten
# b0: 0.5
# b1: 0.3
# type: cos
# a: 2.
# b: 3.

updater:
# type: gauss_newton
  type: levenberg_marquardt
  weight: 0.0001

optimizer:
  tolerance: 0.001

plotter:
# type: residual2d
# grid_num: 200
  type: param2d
  param_range: [5.5, 5.5]
  grid_num: 100

#once: True
