model:
  type: michaelis_menten
# type: circle2d
# type: line2d

init_param: [10., 10.]

updater:
# type: gauss_newton
  type: levenberg_marquardt
  weight: 0.1

optimizer:
  tolerance: 0.0001

plotter:
  type: residual2d
  grid_num: 200

once: False
