model:
  type: michaelis_menten
# type: line2d

init_param: [20., 50.]

updater:
# type: gauss_newton
  type: levenberg_marquardt
  weight: 0.1

optimizer:
  tolerance: 0.0001

plotter:
  type: residual2d
  grid_num: 200

once: False
