context:
  type: clickable
  x_range: [-20., 20.]
  x_step_ratio: 0.05
# type: scan_range
# x_range: [-20., 20.]
# x_step_ratio: 0.01
# cycle_sec: 0.002  # sec
model:
# type: line2d
# a: 5.
# b: 2.
# type: curve2d_2order
# a: -3.
# b: -2.
# c: 5.
  type: curve2d_3order
  a: 1.
  b: 1.
  c: 1.
  d: 1.
# type: michaelis_menten
# b0: 0.3
# b1: 0.5
# type: cos
# a: 2.
# b: 2.

