#!/usr/bin/env python
# -*- coding: utf-8 -*-
from fgs_opt_from_scratch import (
        newton_models, optimizer)

if __name__ == '__main__':
    data = [[0.038, 0.05],
            [0.194, 0.127],
            [0.425, 0.094],
            [0.626, 0.2122],
            [1.253, 0.2729],
            [2.5, 0.2665],
            [3.74, 0.3317]]

    target = newton_models.MichaelisMentenEquation()
    target.update([0.9, 0.2])

    newton = optimizer.Newton(target, data)

    print('initial param   : {}'.format(target.get_param()))
    print('initial residual: {}'.format(newton.residual()))

    print('optimize...')
    num_iteration = newton.optimize()

    print('num of iteration: {}'.format(num_iteration))
    print('final param     : {}'.format(target.get_param()))
    print('final residual  : {}'.format(newton.residual()))
