#!/usr/bin/env python
# -*- coding: utf-8 -*-
import cv2
from fgs_opt_from_scratch import (
        models, optimizers, updaters)
import yaml
from sys import exit, argv

if __name__ == '__main__':
    if len(argv) != 3:
        print('usage: rosrun fgs_opt_from_scratch optimize config_path data_path')
        exit(-1)

    with open(argv[1], 'r') as f:
        config_dict = yaml.load(f)

    # データ
    cv_yaml = cv2.FileStorage(argv[2], cv2.FileStorage_READ)
    data = cv_yaml.getNode('data').mat()

    # モデル
    model = models.create(config_dict['model'])
    model.update(config_dict['init_param'])

    # パラメータ更新関数
    update_func = updaters.create(config_dict['updater'])

    optimizer = optimizers.create(model, data, update_func, config_dict['optimizer'])

    print('initial param               : {}'.format(model.get_param()))
    print('initial error of sum squares: {}'.format(optimizer.ess()))

    print('optimize...')
    num_iteration = optimizer.optimize()

    print('num of iteration          : {}'.format(num_iteration))
    print('final param               : {}'.format(model.get_param()))
    print('final error of sum squares: {}'.format(optimizer.ess()))
