#!/usr/bin/env python
# -*- coding: utf-8 -*-
from sys import argv

import numpy as np
import yaml

from fgs_opt_from_scratch import (
        taylor_functions as functions,
        plotters
)

if __name__ == '__main__':
    if len(argv) != 2:
        print('usage: rosrun fgs_opt_from_scratch view_taylor config_path')
        exit(-1)

    f = open(argv[-1], 'r')
    config_dict = yaml.load(f)

    func = functions.create(config_dict)
    x_range = config_dict['x_range']
    plotter = plotters.ClickableTaylorPlotter(func, x_range)
    plotter.show()

    try:
        input('press enter to terminate')
    except:
        pass

