#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np

from fgs_opt_from_scratch import functions
import matplotlib.pylab as plt

func = functions.Curve2dSampleFunc(2, 3, -1)
x_array = [x for x in np.arange(-50., 50., 1)]
y_array = [func.fx(x) for x in x_array]

def on_click(event):
    plt.clf()
    if event.xdata is not None:
        x = event.xdata
        taylor_x_array = []
        taylor1_y_array = []
        taylor2_y_array = []
        for new_x in np.arange(-70. + x, 70. + x, 1):
            taylor_x_array.append(new_x)
            taylor1_y_array.append(func.taylor([x, func.fx(x)], new_x, d=1))
            taylor2_y_array.append(func.taylor([x, func.fx(x)], new_x, d=2))

        plt.plot(x_array, y_array, marker='o')
        plt.plot(taylor_x_array, taylor1_y_array, marker='x')
        plt.plot(taylor_x_array, taylor2_y_array, marker='.')

        plt.show()
    else:
        print('invalid')

if __name__ == '__main__':
    fig = plt.figure()

    fig.canvas.mpl_connect('button_press_event', on_click)
    plt.plot(x_array, y_array, marker='o')

    plt.show()
