#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np

from fgs_opt_from_scratch import functions, plotter


if __name__ == '__main__':
    func = functions.Curve2dSampleFunc(2, 3, -1)

    data = [[x, func.fx(x)] for x in np.arange(-10., 10., 1)]
    nv = [func.normal_vector(point) for point in data]
    tangents = []
    for i in range(len(data)):
        nv_ele = nv[i]
        tangent = [[x, func.tangent(nv_ele, x)] for x in np.arange(x - 10., x + 10., 2)]
        tangents.append(tangent)

    plotter.scatter2d(data)
    plotter.scatter2d(nv)

    for tangent in tangents:
        plotter.scatter2d(tangent)
